### ISSUE TITLE
Each code execution in a different container

### ISSUE THREAD

**Issue by cs20s013** [budukhyash/remote-code-execution-engine#32]
I have a doubt with respect to the implementation. Which part of the code makes sure that each code execution is run in a separate container? In my understanding, if different user codes are run in the same container, it may pose a security risk which we wanted to avoid.

**Comment by budukhyash** [comment]
@cs20s013 So once the worker picks up a job, it'll only pick the next job after the current job is completed.
By this we make sure that we only run one user's code in a container at any given time.
