### ISSUE TITLE
javac not found

### ISSUE THREAD

**Issue by itiwarishubham1** [budukhyash/remote-code-execution-engine#5]
Whenever we try to excute java code it gives this error response in return but working fine with c, c++, python
**Input:**

{
	"src":"class Main{public static void main(String[] args){System.out.println(\"Test\");}}",
	"stdin":"",
	"lang":"java",
	"timeout":5
}	
**{"output":"","stderr":"sh: 1: javac: not found\n","status":"error\n","submission_id":"f70f994cb0c533893d25"}**

**Comment by gouseferoz** [comment]
I am also facing the same issue. Any workaround here?

**Comment by yash-ultrahuman** [comment]
@gouseferoz I have added a fix for this,
Can you please check out this branch [`adding-java-support`](https://github.com/budukhyash/remote-code-execution-engine/tree/adding-java-support) and let me know?
Fixed this long pending issue, please do let me know.
Delayed my dinner for this fix, please give this a repo a star 🙈

**Comment by gouseferoz** [comment]
Hi @yash-ultrahuman I have tried running the below code:
```
{
	"src":"public class Main {\r\n\r\n  public static void main(String[] args) {\r\n\r\n    int num = 139;\r\n    boolean flag = false;\r\n    for (int i = 2; i <= num / 2; ++i) {\r\n      // condition for nonprime number\r\n      if (num % i == 0) {\r\n        flag = true;\r\n        break;\r\n      }\r\n    }\r\n\r\n    if (!flag)\r\n      System.out.println(num + \" is a prime number.\");\r\n    else\r\n      System.out.println(num + \" is not a prime number.\");\r\n  }\r\n}",
	"stdin":"123",
	"lang":"java",
	"timeout":15
}
```

and in the docker console, I got a message `error`. When I tried to get the results of the execution, I can see the response as `status: processing` and the compiler doesn't work if I send another request and returns the status as `Queued`

**Comment by yash-ultrahuman** [comment]
@gouseferoz 
Can you pull the latest `adding-java-support` branch and try again?
instead of `public class Main` use class Main

`{
    "src": "class Main {\r\n\r\n  public static void main(String[] args) {\r\n\r\n    int num = 142;\r\n    boolean flag = false;\r\n    for (int i = 2; i <= num / 2; ++i) {\r\n      // condition for nonprime number\r\n      if (num % i == 0) {\r\n        flag = true;\r\n        break;\r\n      }\r\n    }\r\n\r\n    if (!flag)\r\n      System.out.println(num + \" is a prime number.\");\r\n    else\r\n      System.out.println(num + \" is not a prime number.\");\r\n  }\r\n}",
    "stdin": "123",
    "lang": "java",
    "timeout": 15
}`

**Comment by gouseferoz** [comment]
Thanks @yash-ultrahuman The java is working now.
